# Generated by Django 4.2.1 on 2023-07-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('Gender', models.CharField(default=None, max_length=15)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('mobile', models.CharField(max_length=30)),
                ('DOB', models.DateField(default=None)),
                ('aadhaar_number', models.CharField(default=0, max_length=30)),
                ('account_type', models.CharField(default=None, max_length=50)),
                ('account_number', models.IntegerField(default=0)),
                ('country', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('street', models.CharField(default=None, max_length=50)),
                ('pincode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('account_number', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
